/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bird.glb --transform --output src/components/Bird.jsx 
Files: public/models/bird.glb [190.83KB] > C:\Users\PC\Downloads\threejs-practice-main\threejs-practice-main\src\components\bird-transformed.glb [60.3KB] (68%)
Author: Blender Artist (https://sketchfab.com/moizmuhammad373)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bird-e93a906eb38343c4a14458a637136329
Title: Bird
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'

export default function Bird(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/bird-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // Sketch-style material
  const paperMaterial = React.useMemo(() => new THREE.MeshStandardMaterial({
    color: '#000000',
    roughness: 0.8,
  }), [])

  useEffect(() => {
    const anime = Object.values(actions)[0]
    if (anime) anime.play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <primitive object={nodes._rootJoint_1} />
        <primitive object={nodes._rootJoint_2} />
        <primitive object={nodes._rootJoint_3} />
        <primitive object={nodes._rootJoint_4} />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={paperMaterial}
          skeleton={nodes.Object_9.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
          castShadow
          receiveShadow
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={paperMaterial}
          skeleton={nodes.Object_10.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
          castShadow
          receiveShadow
        />



        <skinnedMesh
          name="Object_74"
          geometry={nodes.Object_74.geometry}
          material={paperMaterial}
          skeleton={nodes.Object_74.skeleton}
          position={[-0.39, 0.022, 0.949]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.083}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/bird-transformed.glb')
