/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_medieval_island.glb --transform --keepnames --output src/components/Island.jsx 
Files: public/models/low_poly_medieval_island.glb [2.23MB] > C:\Users\PC\Downloads\threejs-practice-main\threejs-practice-main\src\components\low_poly_medieval_island-transformed.glb [310.91KB] (86%)
Author: Boooooop (https://sketchfab.com/boooop)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-medieval-island-361f02265937462a8969d78c5be1fc6c
Title: Low Poly Medieval Island
*/

import React, { useMemo, forwardRef } from 'react'
import { useGLTF, Edges, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

const Island = forwardRef(({ material, ...props }, ref) => {
  const { nodes } = useGLTF('/models/low_poly_medieval_island-transformed.glb')
  const scroll = useScroll()

  // Unified Lighter Yellow Palette
  const palette = useMemo(() => ({
    stone: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.8 }),
    grass: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.9 }),
    wood: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.9 }),
    roof: new THREE.MeshStandardMaterial({ color: '#fdfae0', roughness: 0.8 }),
    white: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.8 }),
    pollen: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.5 }),
    plaster: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.9 }),
    pavement: new THREE.MeshStandardMaterial({ color: '#fefae0', roughness: 0.9 }),
  }), [])

  useFrame(() => {
    // --- FINAL REVEAL FADE-OUT ---
    const finalFade = THREE.MathUtils.smoothstep(scroll.offset, 0.94, 0.97)
    const opacity = Math.max(0, 1 - finalFade)

    Object.values(palette).forEach((mat) => {
      mat.opacity = opacity
      mat.transparent = opacity < 1
      mat.depthWrite = opacity > 0.5
    })

    if (ref.current) ref.current.visible = opacity > 0
  })

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh name="polySurface31_Stone_0" geometry={nodes.polySurface31_Stone_0.geometry} material={palette.stone} position={[-0.001, -0.032, -0.461]} scale={[0.293, 0.3, 0.293]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="polySurface32_moss_0" geometry={nodes.polySurface32_moss_0.geometry} material={palette.grass} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="polySurface32_Dirt_0" geometry={nodes.polySurface32_Dirt_0.geometry} material={palette.pavement} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="polySurface32_Grass_0" geometry={nodes.polySurface32_Grass_0.geometry} material={palette.grass} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="calendula-flower5_green_0" geometry={nodes['calendula-flower5_green_0'].geometry} material={palette.grass} position={[-0.083, 0, -0.108]} scale={0.17}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="calendula-flower5_White_0" geometry={nodes['calendula-flower5_White_0'].geometry} material={palette.white} position={[-0.083, 0, -0.108]} scale={0.17}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="calendula-flower5_Pollen_0" geometry={nodes['calendula-flower5_Pollen_0'].geometry} material={palette.pollen} position={[-0.083, 0, -0.108]} scale={0.17}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="well_cobble_0" geometry={nodes.well_cobble_0.geometry} material={palette.stone} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="well_Wood_0" geometry={nodes.well_Wood_0.geometry} material={palette.wood} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="well_Roof_0" geometry={nodes.well_Roof_0.geometry} material={palette.roof} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="well_Metal_0" geometry={nodes.well_Metal_0.geometry} material={palette.pavement} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]}>
        <Edges color="#000000" threshold={20} />
      </mesh>
      <mesh name="polySurface10_plaster_0" geometry={nodes.polySurface10_plaster_0.geometry} material={palette.plaster} position={[1.555, -0.755, 0.356]} rotation={[0, -0.262, 0]} scale={0.234}>
        <Edges color="#000000" threshold={20} />
      </mesh>
    </group>
  )
})

export default Island

useGLTF.preload('/models/low_poly_medieval_island-transformed.glb')
