/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_medieval_island.glb --transform --keepnames --output src/components/Island.jsx 
Files: public/models/low_poly_medieval_island.glb [2.23MB] > C:\Users\PC\Downloads\threejs-practice-main\threejs-practice-main\src\components\low_poly_medieval_island-transformed.glb [310.91KB] (86%)
Author: Boooooop (https://sketchfab.com/boooop)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-medieval-island-361f02265937462a8969d78c5be1fc6c
Title: Low Poly Medieval Island
*/

import React, { useMemo, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

const Island = forwardRef(({ material, ...props }, ref) => {
  const { nodes } = useGLTF('/models/low_poly_medieval_island-transformed.glb')

  // Enhanced Palette (Sketch-style colors)
  const palette = useMemo(() => ({
    stone: new THREE.MeshStandardMaterial({ color: '#c2b2a2', roughness: 0.8 }), // Muted grey-parchment
    grass: new THREE.MeshStandardMaterial({ color: '#b2bc8c', roughness: 0.9 }), // Muted sage green
    wood: new THREE.MeshStandardMaterial({ color: '#a68a64', roughness: 0.9 }),  // Muted brown
    roof: new THREE.MeshStandardMaterial({ color: '#c98a7d', roughness: 0.8 }),  // Muted terracotta
    white: new THREE.MeshStandardMaterial({ color: '#f5f5f5', roughness: 0.8 }), // Clean paper
    pollen: new THREE.MeshStandardMaterial({ color: '#d4af37', roughness: 0.5 }), // Golden accent
    plaster: new THREE.MeshStandardMaterial({ color: '#faefe6', roughness: 0.9 }), // Lighter parchment
    pavement: new THREE.MeshStandardMaterial({ color: '#968c83', roughness: 0.9 }), // Darker stone
  }), [])

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh name="polySurface31_Stone_0" geometry={nodes.polySurface31_Stone_0.geometry} material={palette.stone} position={[-0.001, -0.032, -0.461]} scale={[0.293, 0.3, 0.293]} />
      <mesh name="polySurface32_moss_0" geometry={nodes.polySurface32_moss_0.geometry} material={palette.grass} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]} />
      <mesh name="polySurface32_Dirt_0" geometry={nodes.polySurface32_Dirt_0.geometry} material={palette.pavement} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]} />
      <mesh name="polySurface32_Grass_0" geometry={nodes.polySurface32_Grass_0.geometry} material={palette.grass} position={[-0.001, -0.032, 0.087]} scale={[0.293, 0.3, 0.293]} />
      <mesh name="calendula-flower5_green_0" geometry={nodes['calendula-flower5_green_0'].geometry} material={palette.grass} position={[-0.083, 0, -0.108]} scale={0.17} />
      <mesh name="calendula-flower5_White_0" geometry={nodes['calendula-flower5_White_0'].geometry} material={palette.white} position={[-0.083, 0, -0.108]} scale={0.17} />
      <mesh name="calendula-flower5_Pollen_0" geometry={nodes['calendula-flower5_Pollen_0'].geometry} material={palette.pollen} position={[-0.083, 0, -0.108]} scale={0.17} />
      <mesh name="well_cobble_0" geometry={nodes.well_cobble_0.geometry} material={palette.stone} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]} />
      <mesh name="well_Wood_0" geometry={nodes.well_Wood_0.geometry} material={palette.wood} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]} />
      <mesh name="well_Roof_0" geometry={nodes.well_Roof_0.geometry} material={palette.roof} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]} />
      <mesh name="well_Metal_0" geometry={nodes.well_Metal_0.geometry} material={palette.pavement} position={[1.113, 1.849, 5.796]} rotation={[-1.573, -0.065, -0.034]} scale={[0.862, 0.862, 0.669]} />
      <mesh name="polySurface10_plaster_0" geometry={nodes.polySurface10_plaster_0.geometry} material={palette.plaster} position={[1.555, -0.755, 0.356]} rotation={[0, -0.262, 0]} scale={0.234} />
    </group>
  )
})

export default Island

useGLTF.preload('/models/low_poly_medieval_island-transformed.glb')
